package pl.kacpermajkowski.ChunkyPlots.basic;

public enum Flag {
	PLACE_STRANGER,
	PLACE_MEMBER,

	BREAK_STRANGER,
	BREAK_MEMBER,

	IGNITE_MEMBER,
	IGNITE_STRANGER,

	EXPLODE_MEMBER,
	EXPLODE_STRANGER,

	PVP,
	PVE,
	EVE,

	ANIMAL_SPAWNING,
	MOB_SPAWNING,

	CREEPER_EXPLOSION,
	ENDERMAN_GRIEFING,
	REDSTONE,

	BLOCK_INTERACT_STRANGER,
	BLOCK_INTERACT_MEMBER,

	ENTITY_TAME_STRANGER,
	ENTITY_TAME_MEMBER,

	ENTITY_LEASH_STRANGER,
	ENTITY_LEASH_MEMBER,

	ENTITY_SHEAR_MEMBER,
	ENTITY_SHEAR_STRANGER,

	ENTITY_DAMAGE_STRANGER,
	ENTITY_DAMAGE_MEMBER,

	ENTITY_INTERACT_STRANGER,
	ENTITY_INTERACT_MEMBER,

	VEHICLE_DAMAGE_STRANGER,
	VEHICLE_DAMAGE_MEMBER,

	VEHICLE_ENTER_STRANGER,
	VEHICLE_ENTER_MEMBER,

	SPLASH_POTION_MEMBER,
	SPLASH_POTION_STRANGER,

	FALL_DAMAGE,
	DROWNING_DAMAGE,

	EXTERNAL_PISTON_PROTECTION,
	EXTERNAL_FIRE_PROTECTION;

	public static Flag getByName(String name){
		for(Flag flag:values()){
			if(flag.name().equalsIgnoreCase(name)){
				return Flag.valueOf(name.toUpperCase());
			}
		}
		return null;
	}
}
