pluginPrefix: "&e&lChunkyPlots"
prefixSpacer: " &8&l» &7"
usePrefix: true

plotItem:
  material: "NOTE_BLOCK"
  name: "&6&lBLOK DZIALKI"
  lore:
    - "&7Ten blok umozliwi ci zajecie chunku"
    - "&7tak, aby nikt obcy nie mogl"
    - "&7zniszczyc ci dzialki"

defaultFlags:
  PLACE_STRANGER: false
  PLACE_MEMBER: true
  BREAK_STRANGER: false
  BREAK_MEMBER: true
  PVP: false
  PVE: true
  EVE: false
  ANIMAL_SPAWNING: true
  MOB_SPAWNING: true
  CREEPER_EXPLOSION: true
  ENDERMAN_GRIEFING: true
  REDSTONE: true
  BLOCK_INTERACT_STRANGER: false
  BLOCK_INTERACT_MEMBER: true
  ENTITY_TAME_STRANGER: false
  ENTITY_TAME_MEMBER: true
  ENTITY_LEASH_STRANGER: false
  ENTITY_LEASH_MEMBER: true
  ENTITY_DAMAGE_STRANGER: false
  ENTITY_DAMAGE_MEMBER: true
  ENTITY_INTERACT_STRANGER: false
  ENTITY_INTERACT_MEMBER: true
  VEHICLE_DAMAGE_STRANGER: false
  VEHICLE_DAMAGE_MEMBER: true
  VEHICLE_ENTER_STRANGER: false
  VEHICLE_ENTER_MEMBER: true
  SPLASH_POTION_MEMBER: true
  SPLASH_POTION_STRANGER: false
  FALL_DAMAGE: true
  DROWNING_DAMAGE: true
  EXTERNAL_PISTON_PROTECTION: true
  EXPLODE_MEMBER: true
  EXPLODE_STRANGER: false

messages:
  notPermitted: "&cNie masz uprawnień, aby to zrobić!"
  enteredPlot: "&aWkroczyłeś na działkę gracza &7{plotOwnerName}"
  leftPlot: "&cOpuściłeś działkę gracza &7{plotOwnerName}"
  addedMemberToPlot: "&aDodałeś gracza &f{user} &ado działki!"
  removedMemberFromPlot: "&cUsunąłeś gracza &f{user} &cz działki"
  plotCreated: "&aPomyślnie utworzono działkę o ID &8(&7{plotID}&8)"
  plotDeleted: "&cPomyślnie usunięto działkę o ID &8(&7{plotID}&8)"
  errorUnspecified: "&cPojawił się bliżej nieprzewidziany błąd. Zgłoś ten fakt administratorowi"
  addSelfToPlot: "&cNie możesz dodać samego siebie do działki!"
  notOwner: "&cNie możesz tego zrobić, bo nie jesteś właścicielem tej działki!"
  nullUser: "&cGracz o nicku &f{userName} &cnie istnieje!"
  nullPlot: "&cDziałka na której stoisz lub której koordynaty wpisałeś nie istnieje!"
  senderNotPlayer: "&cThis command can be performed only by a player!"
  plotAlreadyExists: "&cW tym miejscu istnieje już działka!"
  settedFlag: "&aPomyślnie ustawiono flagę &f{flagName} &ana &f{flagValue}"
  flagValueOnPlot: "&aFlaga &f{flagName} &aprzyjmuje na tej działce wartość &f{flagValue}"
  avaibleFlags: "&aLista dostępnych flag:"
  unknownFlag: "&cNie odnaleziono flagi o nazwie &f{flagName}"
  wrongFlagValue: "&cPodałeś niepoprawną wartość! Wpisz &ftrue &c albo &ffalse"
  cannotAddSelfAsMember: "&cWłaściciel działki nie może być jej członkiem!"
  cannotAddSelfToBlacklist: "&cWłaściciel działki nie może być na jej blackliście!"
  addedToBlacklist: "&aPomyślnie dodano gracza &f{user} &ado blacklisty działki o ID &8(&7{plotID}&8)"
  removedFromBlacklist: "&aPomyślnie usunięto gracza &f{user} &az blacklisty działki o ID &8(&7{plotID}&8)"
  defaultVisitPointDescription: "&aOto punkt wizyt gracza &f{userName}"
  deletedVisitPoint: "&cPomyślnie usunięto punkt o nazwie &r{visitPointName}"
  nullVisitPoint: "&cPunkt o nazwie &f{visitPointName} &cnie istnieje!"
  visitPointClosed: "&cPunkt wizyt &r{visitPointName}&c jest aktualnie zamknięty!"
  visitPointNotSafe: "&cPunkt wizyt &r{visitPointName}&c jest niebezpieczny! Anulowano teleportację!"
  notVisitPointOwner: "&cNie możesz tego zrobić, bo nie jesteś właścicielem punktu!"
  createdVisitPoint: "&aUtworzono punkt wizyt o nazwie &r{visitPointName}"
  visitPointAlreadyExists: "&cPunkt wizyt o nazwie &r{visitPointName}&c już istnieje"
  marketPuttedOnAuction: "&aPomyślnie wystawiono działkę o ID &8(&7{plotID}&8) &a na sprzedaż za &e%price%"
  marketCancelledAuction: "&aPomyślnie anulowano sprzedaż działki o ID &8(&7{plotID}&8)"
  marketBoughtPlot: "&aPomyślnie zakupiono działkę o ID &8(&7{plotID}&8)"
  blacklistAddedToPlot: "&aDodano gracza &r{user} &ado czarnej listy działki"
  blacklistRemovedFromPlot: "&aUsunięto gracza &r{user} &az czarnej listy działki"
  flagSetOnPlot: "&aUstawiono wartość &r{flagValue} &afladze &r{flagName}&a na działce"
  flagSetOnGroup: "&aUstawiono wartość &r{flagValue} &afladze &r{flagName} &ana wszystkich działkach grupy &r{groupName}"
  flagValuesInGroupAreDifferent: "&eFlaga &f{flagName} &eprzyjmuje na działkach tej grupy różne wartości."
  cannotAddOwnerToBlacklist: "&cNie można dodać właściciela działki do whitelisty"
  cannotAddOwnerAsMember: "&cNie można dodać właściciela działki jako jej członka"
  playerIsAlreadyBlacklisted: "&cGracz &r{user} &cznajduje się już na whiteliście"
  playerIsAlreadyAMember: "&cGracz &r{user} &cjest już dodany do działki"
  nullGroup: "&cGrupa o nazwie &r{groupName} &cnie istnieje!"
  cannotDeleteDefaultGroup: "&cNie możesz usunąć domyślnej grupy o nazwie &rall"
  cannotRemovePlotFromDefaultGroup: "&cNie możesz usuwać działek z domyślnej grupy o nazwie &rall"
  plotNotInGroup: "&cWskazana działka nie znajduje się w grupie &r{groupName}"
  plotAlreadyInGroup: "&cWskazana działka znajduje się już w grupie o nazwie &r{groupName}"
  cannotAddPlotToDefaultGroup: "&cNie możesz dodawać działek do domyśłnej grupy o nazwie &rall"
  groupAlreadyExists: "&cGrupa o nazwie &r{groupName} &cjuż istnieje!"
  groupCreate: "&aPomyślnie utworzono grupę o nazwie &r{groupName}"
  groupDelete: "&cPomyślnie usunięto grupę o nazwie &r{groupName}"
  plotAddedToGroup: "&aPomyślnie dodano działkę do grupy o nazwie &r{groupName}"
  plotRemovedFromGroup: "&cPomyślnie usunięto działkę z grupy o nazwie &r{groupName}"
  teleportingToVisitPoint: "&aTrwa teleportacja do punktu &r{visitPointName}&a. &eNie ruszaj się przez 5 sekund!"
  teleportedToVisitPoint: "&aPomyślnie przeteleportowano do punktu &r{visitPointName}"
  teleportCancelled: "&cPoruszyłeś się, anulowano teleportację!"


